INSERT INTO festival (game_id, name, description, image_url, link_video, festival_status) VALUES
(1, 'Hội Gióng', $desc$Hội Gióng là một trong những lễ hội truyền thống tiêu biểu nhất của Việt Nam, được tổ chức nhằm tưởng niệm và ghi nhớ công ơn của Thánh Gióng, vị anh hùng huyền thoại có công đánh đuổi giặc Ân, biểu tượng cho tinh thần yêu nước, ý chí quật cường và sức mạnh đoàn kết của dân tộc. Lễ hội phản ánh tín ngưỡng thờ anh hùng dân tộc, gắn với truyền thống dựng nước và giữ nước của người Việt từ thời kỳ sơ khai.
Hiện nay, Hội Gióng được tổ chức trọng điểm tại hai địa điểm chính ở Hà Nội:
Hội Gióng đền Sóc tại Sóc Sơn (trong 3 ngày từ mùng 6 đến mùng 8 tháng Giêng hằng năm): nơi gắn với sự tích Thánh Gióng bay về trời sau khi hoàn thành sứ mệnh 
Hội Gióng Phù Đổng tại Gia Lâm (từ ngày 7 đến ngày 9 tháng 4 Âm lịch hằng năm): quê hương của Thánh Gióng, nơi tái hiện sinh động các chặng đường đánh giặc qua nghi lễ và diễn xướng dân gian. 
Các hoạt động trong lễ hội bao gồm nghi thức tế lễ trang nghiêm, rước kiệu, diễn cảnh đánh giặc và các hình thức sinh hoạt văn hóa cộng đồng.
Với giá trị lịch sử, văn hóa và tinh thần đặc biệt, Hội Gióng là lễ hội đầu tiên của Việt Nam được UNESCO công nhận là Di sản văn hóa phi vật thể của nhân loại, khẳng định vai trò quan trọng của lễ hội trong việc bảo tồn bản sắc văn hóa và truyền thống dân tộc Việt Nam.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Hội Lim (12–14/1 âm lịch – Bắc Ninh)', $desc$Hội Lim, hay còn được gọi là Hội chùa làng Lim, là lễ hội truyền thống tiêu biểu của vùng Kinh Bắc (Bắc Ninh) diễn ra 12–14/1 âm lịch hằng năm (chính hội ngày 13). Theo các ghi chép lịch sử, nguồn gốc của Hội Lim bắt nguồn từ những lễ hội ca hát và hội chùa cổ của cư dân địa phương từ xa xưa, gắn liền với sinh hoạt văn hóa dân gian và tín ngưỡng cộng đồng. Lễ hội còn được cho là có liên hệ biểu tượng với tiếng hát Trương Chi trong truyện cổ tích Trương Chi – Mỵ Nương, phản ánh vai trò đặc biệt của tiếng hát và tình cảm giao duyên trong đời sống tinh thần người Việt.
Từ thế kỷ XIX đến nửa đầu thế kỷ XX, Hội Lim trở thành không gian văn hóa – nghệ thuật đặc sắc của Kinh Bắc, dù từng gián đoạn trong thời kỳ chiến tranh, lễ hội đã được khôi phục và tổ chức thường niên sau khi đất nước thống nhất. Không chỉ mang tính lễ hội đầu xuân, Hội Lim còn có ý nghĩa quan trọng trong việc bảo tồn và truyền dạy dân ca Quan họ Bắc Ninh – Di sản Văn hóa Phi vật thể của nhân loại được UNESCO công nhận năm 2009. Các nghi lễ chính gồm dâng hương, rước và tế lễ, cầu bình an và mùa màng bội thu. Phần hội sôi nổi với trò chơi dân gian, đặc biệt là hát Quan họ giao duyên trên sông Tiêu.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ Khao Lề Thế Lính Hoàng Sa (20/2 âm lịch)', $desc$Vào đầu thế kỷ XVII, dưới thời các chúa Nguyễn, đội Hoàng Sa được thành lập gồm những ngư dân giỏi đi biển ở vùng Sa Kỳ và đảo Lý Sơn (Quảng Ngãi) để ra Hoàng Sa – Trường Sa khai thác hải vật, đo đạc thủy trình, tuần phòng và cắm mốc khẳng định chủ quyền. Mỗi năm, đội lính xuất phát vào tháng 2–3 âm lịch và trở về vào tháng 8 âm lịch, do hiểm nguy trên biển, nhiều người đã ra đi không trở lại, để lại những mộ gió trên đảo Lý Sơn.
Để tưởng nhớ những người đã hy sinh và cầu bình an cho những người sắp ra khơi, người dân Lý Sơn tổ chức Lễ Khao lề Thế lính Hoàng Sa vào tháng 2 âm lịch hằng năm. Lễ mang ý nghĩa cúng tế tổ tiên, tri ân đội lính Hoàng Sa – Trường Sa, đồng thời gửi gắm niềm tin và ước nguyện về sự che chở, bình an cho những chuyến biển nối tiếp.
Các hoạt động chính gồm:
Nghi lễ dâng hương, cúng tế, rước sắc và lễ thả thuyền mô hình ra biển để tưởng niệm đội lính Hoàng Sa.
Lễ hội đua thuyền truyền thống Tứ Linh - một hoạt động mang tính cộng đồng và văn hóa biển.
Các sinh hoạt văn hóa đi kèm như lễ hoa đăng, hát bội, múa lân… góp phần tạo không khí lễ hội. 
Với giá trị lịch sử và văn hóa sâu sắc, Lễ Khao Lề Thế Lính Hoàng Sa đã được Bộ Văn hóa, Thể thao và Du lịch Việt Nam công nhận là Di sản Văn hóa Phi vật thể quốc gia (loại hình Tập quán xã hội và tín ngưỡng) kể từ năm 2013.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội xuân Yên Tử (tháng 1–3 âm lịch)', $desc$Lễ hội xuân Yên Tử là lễ hội tâm linh lớn của miền Bắc, gắn liền với Phật hoàng Trần Nhân Tông – vị vua anh minh nhà Trần, người sáng lập Thiền phái Trúc Lâm mang đậm tinh thần Phật giáo Việt Nam. Lễ hội được tổ chức tại khu di tích danh thắng Yên Tử (Quảng Ninh), nơi được xem là đất tổ của Phật giáo Việt Nam, biểu trưng cho triết lý “tu trong đời”, hòa hợp giữa đạo và đời. (Năm 2025, UNESCO đã chính thức công nhận Quần thể di tích và danh thắng Yên Tử - Vĩnh Nghiêm, Côn Sơn, Kiếp Bạc là Di sản Văn hóa Thế giới)
Về ý nghĩa, lễ hội thể hiện rõ tinh thần nhập thế của Phật giáo Việt Nam – tu tập ngay trong đời sống thường nhật, hài hòa giữa đạo và đời. Đồng thời, lễ hội góp phần bảo tồn các giá trị lịch sử – văn hóa của danh thắng Yên Tử và lan tỏa triết lý sống hướng thiện, cân bằng tâm – thân trong xã hội hiện đại.
Các hoạt động chính trong lễ hội gồm: nghi lễ mở cửa rừng, dâng hương, tụng kinh, lễ cầu quốc thái dân an; lễ khai hội với thỉnh chuông, gióng trống, đóng ấn thiêng Yên Tử; cùng các hoạt động hội như hành hương lên chùa Đồng, tham gia trò chơi dân gian, thưởng thức văn nghệ truyền thống, võ cổ truyền và múa rồng.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Kỳ Yên (tháng 4 âm lịch)', $desc$Lễ hội Kỳ Yên là lễ hội truyền thống nông nghiệp lâu đời, gắn với tín ngưỡng thờ Thành Hoàng và các vị thần bảo hộ làng xã được tổ chức tại các đình làng Nam Bộ, tiêu biểu là Đình Bình Thủy (Cần Thơ). Lễ hội diễn ra tại đình làng như một nghi thức để tạ ơn trời đất, cầu mùa bội thu, cầu an cho làng xóm, đồng thời tưởng nhớ tổ tiên và các bậc tiền nhân có công khai hoang, lập làng. 
Theo truyền thống, lễ hội Kỳ Yên diễn ra hai lần mỗi năm:
Thượng điền (khi vừa thu hoạch xong): từ ngày 12–14 tháng 4 âm lịch
Hạ điền (khi bắt đầu xuống ruộng): ngày 14–15 tháng Chạp âm lịch, chuẩn bị đón năm mới
Các hoạt động trong lễ hội bao gồm: tế lễ tại đình, cúng miễu, múa hát dân gian, trò chơi dân gian cùng các hoạt động văn hóa, văn nghệ và thể thao như: triển lãm sách, hội thi mâm xôi nghệ thuật, lễ hội “Bánh ngon Bình Thủy”, hát tuồng cổ…
Lễ hội không chỉ góp phần duy trì truyền thống văn hóa lúa nước, gắn kết cộng đồng, mà còn là cầu nối giữa quá khứ và hiện tại, giúp bảo tồn và trao truyền các giá trị văn hóa của cha ông cho thế hệ kế tiếp. Nhờ những giá trị lịch sử – văn hóa đặc sắc, lễ hội đã được Bộ Văn hóa, Thể thao và Du lịch công nhận là Di sản văn hóa phi vật thể quốc gia vào năm 2018.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Hội Đua voi Buôn Đôn (tháng 3 dương lịch)', $desc$Hội Đua voi Buôn Đôn là lễ hội truyền thống tiêu biểu của vùng Tây Nguyên, gắn bó mật thiết với đời sống văn hóa của người M'nông . Hội được diễn ra tại Buôn Đôn (Đăk Lăk) nơi được mệnh danh là thủ phủ của loài voi.
Trong quan niệm bản địa, voi không chỉ là vật nuôi lao động mà còn được xem như thành viên của gia đình, giữ vị trí quan trọng trong đời sống tinh thần và sinh hoạt cộng đồng. Voi tượng trưng cho sức mạnh, sự bền bỉ, đồng thời gắn liền với lịch sử khai phá, vận chuyển và lao động của cư dân Tây Nguyên.
Lễ hội bắt nguồn từ truyền thống săn bắt và thuần dưỡng voi, tiêu biểu là Y Thu K'Nul (1827–1938) – người được tôn vinh là “Vua săn voi”, có công gây dựng nghề thuần dưỡng voi ở Buôn Đôn. Khi voi rừng được thuần hóa, chủ voi sẽ tổ chức nghi lễ nhập buôn, từ đó voi được chăm sóc, cúng sức khỏe hằng năm như một thành viên trong buôn làng.
Ngày nay, Hội Đua voi Buôn Đôn không chỉ là dịp sinh hoạt lễ hội đầu năm mà còn là không gian văn hóa phản ánh mối quan hệ gắn bó giữa con người và thiên nhiên, thể hiện bản sắc, tinh thần cộng đồng và truyền thống lâu đời của cư dân Tây Nguyên.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Đền Hùng – Giỗ Tổ Hùng Vương (10/3 âm lịch)', $desc$Giỗ Tổ Hùng Vương là ngày lễ truyền thống mang ý nghĩa đặc biệt trong đời sống tinh thần của người Việt, được tổ chức hằng năm tại Khu di tích lịch sử Đền Hùng, tỉnh Phú Thọ – nơi thờ các Vua Hùng, những vị tổ khai sinh dân tộc Việt Nam. Theo các ghi chép lịch sử, từ thời các triều đại phong kiến như Đinh, Tiền Lê, Lý, Trần đến Hậu Lê, việc thờ cúng Vua Hùng tại Đền Hùng luôn được coi trọng và xem là ngày quốc lễ của đất nước. Các triều đình giao cho người dân địa phương trông nom, tu sửa đền miếu và tổ chức lễ giỗ hằng năm; đổi lại, họ được miễn nhiều nghĩa vụ như sưu thuế và lính dịch. Đến thời vua Khải Định, ngày 10/3 âm lịch chính thức được xác lập là ngày Giỗ Tổ Hùng Vương. Từ năm 2007, ngày lễ này trở thành ngày lễ quốc gia và ngày nghỉ chính thức của Việt Nam.
Trong tâm thức người Việt, Giỗ Tổ Hùng Vương mang ý nghĩa thiêng liêng sâu sắc, là dịp để bày tỏ lòng tri ân đối với các Vua Hùng – những người có công dựng nước và giữ nước, đồng thời giáo dục truyền thống “uống nước nhớ nguồn” cho các thế hệ mai sau. Lễ hội còn góp phần khẳng định cội nguồn chung của dân tộc Việt Nam và quảng bá ra thế giới giá trị của Tín ngưỡng thờ cúng Hùng Vương, di sản văn hóa phi vật thể đã được UNESCO công nhận.
Lễ hội Đền Hùng thường diễn ra từ mùng 1 đến ngày 10 tháng 3 âm lịch, thu hút đông đảo người dân và du khách thập phương về Phú Thọ hành hương. Trước ngày chính hội, nhiều hoạt động truyền thống được tổ chức như gói bánh chưng, giã bánh dày, đánh trống đồng và hành hương lên núi Nghĩa Lĩnh. Trong ngày chính lễ, phần lễ được cử hành trang nghiêm với lễ rước kiệu từ chân núi lên Đền Thượng và lễ dâng hương tưởng niệm các Vua Hùng, phần hội diễn ra sôi nổi với các hoạt động văn hóa, thể thao dân gian như hát Xoan, hát Ghẹo, thi vật, kéo co, bơi trải…, tạo nên không gian lễ hội vừa linh thiêng vừa đậm đà bản sắc văn hóa dân tộc.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Bánh Dân Gian Nam Bộ (Cần Thơ) (tháng 3 âm lịch)', $desc$Lễ hội Bánh Dân Gian Nam Bộ là lễ hội văn hóa – ẩm thực cấp quốc gia, được tổ chức thường niên tại quận Ninh Kiều, thành phố Cần Thơ (khu vực gần Bến Ninh Kiều). Lễ hội thường diễn ra vào tháng 3 âm lịch, gắn với chuỗi ngày lễ lớn của đất nước như Giỗ Tổ Hùng Vương, Ngày Giải phóng miền Nam và Quốc tế Lao động. Đây là sự kiện nhằm giới thiệu, quảng bá và tôn vinh các loại bánh dân gian truyền thống của vùng Nam Bộ, đồng thời tạo không gian để người dân và du khách trải nghiệm nét đặc sắc của văn hóa ẩm thực phương Nam. Thông qua lễ hội, hình ảnh con người miền Tây chân chất, cần cù và sáng tạo được thể hiện rõ nét, góp phần bảo tồn và phát huy các giá trị văn hóa truyền thống gắn liền với nghề làm bánh dân gian.
Lễ hội gồm hai phần chính là phần lễ và phần hội. Phần lễ được tổ chức trang trọng với các nghi thức như lễ dâng bánh tại Đình thần Tân An và lễ khai mạc, thể hiện sự tri ân đối với nghề làm bánh truyền thống của người Nam Bộ. Phần hội diễn ra sôi nổi với hội thi làm bánh dân gian, các chương trình biểu diễn nghệ thuật và khu trưng bày – thưởng thức ẩm thực với hàng trăm gian hàng bánh đa dạng như bánh tét lá cẩm, bánh cống, bánh tráng, bánh da lợn… Bên cạnh đó, lễ hội còn có nhiều trò chơi dân gian và hoạt động giao lưu, tạo điều kiện kết nối các nghệ nhân với doanh nghiệp, góp phần đưa bánh dân gian Nam Bộ vươn xa hơn trong và ngoài nước.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Tết Trung Thu (15/8 âm lịch)', 'Lễ hội truyền thống dành cho trẻ em và gia đình vào rằm tháng 8 âm lịch.', NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội đua bò Bảy Núi (cuối 8 – đầu 9 âm)', $desc$Lễ hội Đua bò Bảy Núi (còn gọi là Hội đua bò Khmer An Giang) là lễ hội văn hóa – thể thao truyền thống đặc sắc của đồng bào Khmer Nam Bộ, gắn liền với lễ Sen Dolta – dịp tưởng nhớ, tri ân tổ tiên. Lễ hội được tổ chức hằng năm vào cuối tháng 8 đến đầu tháng 9 âm lịch (thời điểm bà con chuẩn bị cho vụ lúa mới), tại khu vực Bảy Núi, tỉnh An Giang, luân phiên ở ruộng chùa Tà Miệt (xã Ô Lâm, huyện Tri Tôn) và ruộng chùa Thơ Mít (xã An Cư, thị xã Tịnh Biên). 
Ban đầu, người Khmer đưa bò đến ruộng chùa cày đất để tích phước cho tổ tiên và chuẩn bị vụ mùa mới; về sau, hoạt động này phát triển thành hội đua bò mang tính cộng đồng, trở thành lễ hội văn hóa – thể thao độc đáo chỉ có ở vùng Bảy Núi. Lễ hội được tổ chức nhằm tôn vinh nghề nông truyền thống, sức mạnh và sự khéo léo của con người trong lao động sản xuất, đồng thời gửi gắm ước vọng mưa thuận gió hòa, mùa màng bội thu và cuộc sống ấm no. Các hoạt động tiêu biểu trong lễ hội là các cuộc đua bò trên ruộng bùn, với hai hình thức thi đấu chính gồm đua bò cày và đua bò bừa, tạo nên không khí sôi động, náo nhiệt sau mùa vụ.
Không chỉ mang giá trị giải trí, lễ hội còn có ý nghĩa quan trọng trong việc gắn kết cộng đồng, thắt chặt tình đoàn kết giữa người Khmer và người Kinh. Năm 2016, Lễ hội Đua bò Bảy Núi được Bộ Văn hóa, Thể thao và Du lịch công nhận là Di sản văn hóa phi vật thể quốc gia, khẳng định giá trị văn hóa đặc sắc của lễ hội trong đời sống tinh thần Nam Bộ.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Nghinh Ông', $desc$Lễ hội Nghinh Ông là lễ hội truyền thống đặc sắc của ngư dân ven biển Việt Nam, còn được biết đến với tên gọi lễ hội cúng Cá Ông (cá voi). Lễ hội bắt nguồn từ tín ngưỡng thờ Cá Ông, xuất phát từ văn hóa Chăm và sau đó hòa nhập vào đời sống tâm linh của người Việt và người Hoa vùng ven biển. Ngư dân tin rằng Cá Ông là vị thần bảo hộ, cứu giúp khi ra khơi, giúp sóng yên biển lặng, đánh bắt thuận lợi và trở về an toàn. Lễ hội được tổ chức hàng năm từ ngày 15 đến 17 tháng 8 âm lịch, tại các địa phương nổi tiếng như Cần Giờ (TP. Hồ Chí Minh), Phú Quốc (Kiên Giang) và Cà Mau, nơi có đông đảo cộng đồng ngư dân gắn bó với nghề biển.
Lễ hội Nghinh Ông có ý nghĩa cầu an cho ngư dân, biển lặng gió hòa, mùa đánh bắt bội thu và cuộc sống ấm no, hạnh phúc, đồng thời là dịp tưởng nhớ và tôn thờ “Đức ngài Cá Ông” – biểu tượng của lòng hy sinh và niềm tin của ngư dân. Hoạt động trong lễ hội bao gồm lễ rước kiệu Nam Hải Tướng quân ra biển, nghi lễ tế truyền thống tại lăng ông, cùng các nghi thức cúng tế cầu an. Phần hội diễn ra với cuộc diễu hành ghe thuyền trang trí rực rỡ, múa lân, sư tử, các trò chơi dân gian và các hoạt động giao lưu cộng đồng, tạo nên không khí sôi nổi, linh thiêng và mang đậm bản sắc văn hóa vùng biển.
Lễ hội Nghinh Ông không chỉ là dịp lễ cầu an mà còn giữ gìn, bảo tồn tín ngưỡng và bản sắc văn hóa truyền thống của ngư dân Việt Nam, trở thành một trong những lễ hội tiêu biểu của miền biển Nam Bộ.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội hoa tam giác mạch Hà Giang', $desc$Lễ hội Hoa tam giác mạch Hà Giang là lễ hội văn hóa - du lịch tiêu biểu của tỉnh Hà Giang, gắn với loài cây tam giác mạch - một loại cây lương thực truyền thống lâu đời của đồng bào các dân tộc vùng cao. Từ năm 2015, nhận thấy vẻ đẹp và giá trị văn hóa – kinh tế đặc biệt của loài hoa này, tỉnh Hà Giang đã tổ chức Lễ hội Hoa tam giác mạch như một sản phẩm du lịch sáng tạo, từng bước xây dựng thương hiệu du lịch cho vùng cực Bắc Tổ quốc.
Lễ hội thường diễn ra từ tháng 10 đến tháng 12 hằng năm, cao điểm vào tháng 11, tại các huyện thuộc Cao nguyên đá Đồng Văn như Quản Bạ, Yên Minh, Đồng Văn và Mèo Vạc. Đây là thời điểm hoa nở rộ nhất, phủ sắc hồng – tím trên những triền núi đá tai mèo, tạo nên cảnh quan đặc trưng chỉ có ở Hà Giang.
Lễ hội được tổ chức nhằm quảng bá vẻ đẹp thiên nhiên, bảo tồn bản sắc văn hóa dân tộc và thúc đẩy phát triển du lịch bền vững. Thông qua lễ hội, hoa tam giác mạch không chỉ là cây lương thực hay loài hoa dại mà trở thành biểu tượng văn hóa, sinh kế và niềm tự hào của người dân địa phương.
Trong khuôn khổ lễ hội diễn ra nhiều hoạt động phong phú như tham quan cánh đồng hoa, trình diễn nghệ thuật dân gian, trò chơi truyền thống, trưng bày sản phẩm thủ công – nông sản, ẩm thực vùng cao và các sự kiện văn hóa cộng đồng tại phố cổ Đồng Văn. Lễ hội Hoa tam giác mạch là sự kiện du lịch thường niên quy mô lớn, góp phần lan tỏa hình ảnh Hà Giang đến du khách trong và ngoài nước.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Katê - Ninh Thuận', $desc$Lễ hội Katê Ninh Thuận là lễ hội truyền thống quan trọng bậc nhất của đồng bào Chăm, mang đậm dấu ấn văn hóa Champa xưa. Tên gọi Katê có nguồn gốc từ Katik trong Hindu giáo và Kattika trong tiếng Phạn, theo nghĩa hẹp là lễ cúng diễn ra vào tháng 7 theo lịch Chăm, còn theo nghĩa rộng là dịp tưởng nhớ tổ tiên, thần linh và những người có công với cộng đồng. Trải qua thời gian, lễ hội Katê có sự giao thoa và biến đổi do ảnh hưởng của Ấn Độ giáo và Hồi giáo, thể hiện ở các nghi lễ khác nhau giữa các cộng đồng Chăm Ahier, Chăm Awal và Chăm Islam, dù vẫn giữ những nét tín ngưỡng chung ban đầu.
Katê diễn ra trong 3 ngày, bắt đầu từ ngày 1/7 theo lịch Chăm (khoảng cuối tháng 9 – đầu tháng 10 dương lịch), tại các đền tháp Chăm tiêu biểu ở Ninh Thuận như Po Klong Garai, Po Rome và Po Nagar, sau đó lan tỏa về làng và từng gia đình.
Các nghi lễ chính bắt đầu tại đền tháp với rước y phục thần linh, mở cửa tháp, tắm tượng, mặc y phục cho tượng và đại lễ tế, do các chức sắc tôn giáo chủ trì; tiếp đến là nghi lễ tại làng và kết thúc bằng lễ cúng trong mỗi gia đình. Khi trở về nhà, người lớn tuổi nhất trong tộc họ sẽ thay mặt gia đình dâng lễ lên tổ tiên, con cháu sum họp đông đủ, trang phục chỉnh tề và thành tâm cầu nguyện sức khỏe, làm ăn thuận lợi. Vì vậy, Katê không chỉ mang ý nghĩa tâm linh mà còn là dịp gắn kết gia đình, để những người con xa quê trở về đoàn tụ, củng cố sự bền chặt của cộng đồng người Chăm. Lễ hội Katê đã được công nhận là Di sản văn hóa phi vật thể quốc gia, góp phần khẳng định giá trị văn hóa đặc sắc của người Chăm trong đời sống văn hóa Việt Nam.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Ok Om Bok – Cúng Trăng (tháng 10 âm)', $desc$Lễ hội Ok Om Bok (còn gọi là Lễ Cúng Trăng) là lễ hội truyền thống của đồng bào Khmer Nam Bộ, gắn liền với tín ngưỡng nông nghiệp lúa nước. Lễ hội được tổ chức chủ yếu tại tỉnh Trà Vinh (ngoài ra còn có ở Sóc Trăng, Bạc Liêu…), diễn ra vào rằm tháng 10 âm lịch hằng năm. Lễ hội được tổ chức nhằm tạ ơn Thần Mặt Trăng – vị thần được tin là đã điều hòa thời tiết, mang lại mưa thuận gió hòa, mùa màng bội thu và cuộc sống ấm no cho con người.
Về nguồn gốc – lịch sử, Ok Om Bok xuất phát từ tín ngưỡng thờ thần Mặt Trăng của người Khmer, hình thành từ rất sớm và được duy trì qua nhiều thế hệ như một phần không thể thiếu trong đời sống tâm linh cộng đồng. Đây là dịp để người dân tạ ơn Thần Mặt Trăng vì đã ban phước lành, giúp mùa màng bội thu và cuộc sống ấm no, hạnh phúc. Đồng thời, lễ hội còn thể hiện ước vọng mưa thuận gió hòa, bình an và thịnh vượng cho cộng đồng trong năm mới. Bên cạnh ý nghĩa tâm linh, Ok Om Bok còn là không gian sinh hoạt văn hóa chung, góp phần gắn kết cộng đồng Khmer, tăng cường giao lưu và gìn giữ những giá trị truyền thống lâu đời.
Các hoạt động chính trong lễ hội gồm nghi lễ Cúng Trăng với lễ vật như cốm dẹt, trái cây; nghi thức thả hoa đăng; cùng nhiều hoạt động hội như đua ghe ngo, trò chơi dân gian và biểu diễn nghệ thuật truyền thống. Lễ hội Ok Om Bok đã được Bộ Văn hóa, Thể thao và Du lịch Việt Nam công nhận là Di sản văn hóa phi vật thể quốc gia năm 2015$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Mừng lúa mới của dân tộc Êđê', $desc$Lễ hội Mừng lúa mới của dân tộc Êđê (còn gọi là lễ ăn cơm mới) là lễ hội nông nghiệp truyền thống của người Êđê, được tổ chức tại các buôn làng ở Tây Nguyên, chủ yếu ở Đắk Lắk, vào cuối tháng 11 – đầu tháng 12 dương lịch, khi mùa thu hoạch kết thúc và Tây Nguyên bước vào mùa khô. Lễ hội được tổ chức nhằm tạ ơn trời đất, thần lúa và tổ tiên đã phù hộ cho mùa màng bội thu, đồng thời đánh dấu việc kết thúc vụ mùa cũ và mở đầu cho chu kỳ sản xuất mới.
Lễ hội có nguồn gốc từ nền văn minh nông nghiệp lúa rẫy lâu đời của người Êđê, gắn với tín ngưỡng đa thần và quan niệm lúa có linh hồn. Trong lễ hội, các gia đình thực hiện nghi thức rước hồn lúa về nhà, cúng cơm mới, dâng rượu cần, thịt, lúa gạo để cảm tạ thần linh. Ý nghĩa của lễ hội không chỉ thể hiện lòng biết ơn thiên nhiên mà còn củng cố sự gắn kết gia đình và cộng đồng buôn làng. Các hoạt động tiêu biểu gồm nghi lễ cúng, ăn cơm mới, uống rượu cần, đánh cồng chiêng, múa xoang và sinh hoạt cộng đồng. Lễ hội Mừng lúa mới của người Êđê là một phần quan trọng trong không gian văn hóa cồng chiêng Tây Nguyên – di sản văn hóa phi vật thể đại diện của nhân loại.$desc$, NULL, NULL, 'AVAILABLE'),

(1, 'Lễ hội Cồng chiêng Tây Nguyên', $desc$Lễ hội Cồng chiêng Tây Nguyên được tổ chức nhằm tôn vinh giá trị di sản cồng chiêng, đồng thời góp phần bảo tồn bản sắc văn hóa truyền thống của cư dân Tây Nguyên. Trong quan niệm dân gian, cồng chiêng là phương tiện giao tiếp giữa con người và thế giới thần linh, hiện diện trong nhiều nghi lễ quan trọng như mừng lúa mới, cúng bến nước, lễ bỏ mả hay hôn lễ.
Bắt nguồn từ đời sống tín ngưỡng gắn với nền nông nghiệp lúa rẫy, lễ hội thể hiện tinh thần cộng đồng và sự gắn bó buôn làng, đồng thời là không gian truyền dạy văn hóa cho các thế hệ sau. Các hoạt động tiêu biểu bao gồm trình diễn cồng chiêng, múa xoang, phục dựng nghi lễ truyền thống, giao lưu văn nghệ dân gian, thưởng thức ẩm thực và trưng bày sản phẩm thủ công.
Lễ hội được tổ chức nhằm quảng bá hình ảnh Không gian văn hóa Cồng Chiêng Tây Nguyên đã được UNESCO ghi danh là là Kiệt tác truyền khẩu và Di sản văn hóa phi vật thể của nhân loại, khẳng định vị thế và giá trị đặc biệt của di sản này trên bình diện quốc tế.$desc$, NULL, NULL, 'AVAILABLE');

